sudo: false
language: node_js
node_js:
    - 6
    - 8
    - 9
    - 10

cache:
    directories:
        - node_modules

script:
    - npm run prettier-check
    - npm run build
    - npm run test

notifications:
    email: false
