sudo: false
language: node_js
node_js:
    - 6
    - 8
    - 9
    - 10

cache:
    directories:
        - node_modules
matrix:
    fast_finish: true

jobs:
    include:
        - name: lint
          script: npm run lint
        - name: prettier
          script: npm run prettier-check
        - name: test
          script: npm test

notifications:
    email: false
